// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/build-fund-config.ts

import type { FundConfig } from "../lib/types";

export const FUND_CONFIG: FundConfig[] = [
  {
    "id": "mufg_emaxis_slim_all_country",
    "name": "eMAXIS Slim 全世界株式(ｵｰﾙ･ｶﾝﾄﾘｰ)",
    "providerId": "mufg",
    "expenseRatio": 0.0005775,
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "全世界",
      "先進国・新興国（広域）"
    ]
  },
  {
    "id": "mufg_emaxis_slim_sp500",
    "name": "eMAXIS Slim 米国株式(S&P500)",
    "providerId": "mufg",
    "expenseRatio": 0.000814,
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "米国"
    ]
  },
  {
    "id": "rakuten_plus_all_country",
    "name": "楽天･ﾌﾟﾗｽ･ｵｰﾙｶﾝﾄﾘｰ株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "expenseRatio": 0.000561,
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "全世界",
      "先進国・新興国（広域）"
    ]
  },
  {
    "id": "rakuten_plus_sp500",
    "name": "楽天･ﾌﾟﾗｽ･S&P500ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "expenseRatio": 0.00077,
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "米国"
    ]
  },
  {
    "id": "rakuten_total_us",
    "name": "楽天･全米株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "expenseRatio": 0.00162,
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "daiwa_ifree_fang_plus",
    "name": "iFreeNEXT FANG+ｲﾝﾃﾞｯｸｽ",
    "providerId": "daiwa",
    "expenseRatio": 0.007755,
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "mufg_emaxis_slim_topix",
    "name": "eMAXIS Slim 国内株式(TOPIX)",
    "providerId": "mufg",
    "expenseRatio": 0.00143,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "rakuten_total_world",
    "name": "楽天･全世界株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "expenseRatio": 0.00179,
    "tags": [
      "株式-為替ヘッジなし",
      "先進国・新興国（広域）"
    ]
  },
  {
    "id": "mufg_emaxis_slim_all_country_ex_japan",
    "name": "eMAXIS Slim 全世界株式(除く日本)",
    "providerId": "mufg",
    "expenseRatio": 0.0005775,
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "mufg_emaxis_slim_dev_ex_japan",
    "name": "eMAXIS Slim 先進国株式ｲﾝﾃﾞｯｸｽ(除く日本)",
    "providerId": "mufg",
    "expenseRatio": 0.0009889,
    "tags": [
      "先進国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "rakuten_plus_nikkei225",
    "name": "楽天･ﾌﾟﾗｽ･日経225ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "expenseRatio": 0.00132,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "mufg_emaxis_slim_nikkei225",
    "name": "eMAXIS Slim 国内株式(日経平均)",
    "providerId": "mufg",
    "expenseRatio": 0.00143,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "amone_tawara_nikkei225",
    "name": "たわらﾉｰﾛｰﾄﾞ 日経225",
    "providerId": "amone",
    "expenseRatio": 0.00143,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "amone_tawara_dev",
    "name": "たわらﾉｰﾛｰﾄﾞ先進国株式",
    "providerId": "amone",
    "expenseRatio": 0.0009889,
    "tags": [
      "先進国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "mufg_emaxis_slim_emerging",
    "name": "eMAXIS Slim 新興国株式ｲﾝﾃﾞｯｸｽ",
    "providerId": "mufg",
    "expenseRatio": 0.001518,
    "tags": [
      "新興国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "daiwa_ifree_sp500",
    "name": "iFreeS&P500ｲﾝﾃﾞｯｸｽ",
    "providerId": "daiwa",
    "expenseRatio": 0.00198,
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "rakuten_asset_building_aggressive",
    "name": "【らくらく投資専用】楽天･資産づくりﾌｧﾝﾄﾞ(しっかりｺｰｽ)",
    "providerId": "rakuten",
    "expenseRatio": 0.004915,
    "tags": [
      "バランス",
      "固定配分",
      "中リスク",
      "為替リスク低減"
    ]
  },
  {
    "id": "capital_world_equity_dc",
    "name": "ｷｬﾋﾟﾀﾙ世界株式ﾌｧﾝﾄﾞ(DC年金つみたて専用)",
    "providerId": "capital",
    "expenseRatio": 0.0098,
    "tags": [
      "先進国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "mufg_emaxis_slim_balance_8",
    "name": "eMAXIS Slimﾊﾞﾗﾝｽ(8資産均等型)",
    "providerId": "mufg",
    "expenseRatio": 0.00143,
    "tags": [
      "バランス",
      "固定配分",
      "中リスク",
      "為替リスク低減"
    ]
  },
  {
    "id": "resona_smarti_sp500",
    "name": "Smart-i S&P500ｲﾝﾃﾞｯｸｽ",
    "providerId": "resona",
    "expenseRatio": 0.00242,
    "tags": [
      "北米",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "smt_my_smt_sp500",
    "name": "My SMT S&P500ｲﾝﾃﾞｯｸｽ(ﾉｰﾛｰﾄﾞ)",
    "providerId": "smt",
    "expenseRatio": 0.000968,
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "mufg_tsumitate_topix",
    "name": "つみたて日本株式(TOPIX)",
    "providerId": "mufg",
    "expenseRatio": 0.00198,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "sbi_total_world",
    "name": "SBI･全世界株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "sbi",
    "expenseRatio": 0.001022,
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "smds_dc_tsumitate_japan",
    "name": "三井住友･DCつみたてNISA･日本株ｲﾝﾃﾞｯｸｽﾌｧﾝﾄﾞ",
    "providerId": "smds",
    "expenseRatio": 0.00176,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "mufg_high_dividend_nikkei",
    "name": "日経平均高配当利回り株ﾌｧﾝﾄﾞ",
    "providerId": "mufg",
    "expenseRatio": 0.00693,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "mufg_tsumitate_balance_8",
    "name": "つみたて8資産均等ﾊﾞﾗﾝｽ",
    "providerId": "mufg",
    "expenseRatio": 0.00242,
    "tags": [
      "バランス型"
    ]
  },
  {
    "id": "mufg_tsumitate_nikkei",
    "name": "つみたて日本株式(日経平均)",
    "providerId": "mufg",
    "expenseRatio": 0.00198,
    "tags": [
      "国内",
      "株式"
    ]
  },
  {
    "id": "rakuten_world_ex_us",
    "name": "楽天･全世界株式(除く米国)ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "expenseRatio": 0.00182,
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "mufg_emaxis_slim_global_3region",
    "name": "eMAXIS Slim 全世界株式(3地域均等型)",
    "providerId": "mufg",
    "expenseRatio": 0.0005775,
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ]
  },
  {
    "id": "rakuten_asset_building_balanced",
    "name": "【らくらく投資専用】楽天･資産づくりﾌｧﾝﾄﾞ(なかなかｺｰｽ)",
    "providerId": "rakuten",
    "expenseRatio": 0.004915,
    "tags": [
      "バランス",
      "固定配分",
      "中リスク",
      "為替リスク低減"
    ]
  }
];
