// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/build-funds.ts

import type { Fund } from "../lib/types";

export const FUNDS: Fund[] = [
  {
    "id": "mufg_emaxis_slim_all_country",
    "name": "eMAXIS Slim 全世界株式(ｵｰﾙ･ｶﾝﾄﾘｰ)",
    "providerId": "mufg",
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "全世界",
      "先進国・新興国（広域）"
    ],
    "expenseRatio": 0.0005775,
    "refReturn": {
      "oneYear": 0.34759697293870606,
      "threeYear": 1.0104031209362807,
      "fiveYear": 1.4045245669848003,
      "sinceInception": 2.4012
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_sp500",
    "name": "eMAXIS Slim 米国株式(S&P500)",
    "providerId": "mufg",
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "米国"
    ],
    "expenseRatio": 0.000814,
    "refReturn": {
      "oneYear": 0.3199665831244778,
      "threeYear": 1.093047901653243,
      "fiveYear": 1.673434856175973,
      "sinceInception": 2.9350468220761106
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_plus_all_country",
    "name": "楽天･ﾌﾟﾗｽ･ｵｰﾙｶﾝﾄﾘｰ株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "全世界",
      "先進国・新興国（広域）"
    ],
    "expenseRatio": 0.000561,
    "refReturn": {
      "oneYear": 0.3465703971119134,
      "sinceInception": 0.7665255945183393
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_plus_sp500",
    "name": "楽天･ﾌﾟﾗｽ･S&P500ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "tags": [
      "人気",
      "株式-為替ヘッジなし",
      "米国"
    ],
    "expenseRatio": 0.00077,
    "refReturn": {
      "oneYear": 0.3196936706959983,
      "sinceInception": 0.7776092233009708
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_total_us",
    "name": "楽天･全米株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.00162,
    "refReturn": {
      "oneYear": 0.320368407103101,
      "threeYear": 1.0468388886035642,
      "fiveYear": 1.4882312542923146,
      "sinceInception": 2.9854
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "daiwa_ifree_fang_plus",
    "name": "iFreeNEXT FANG+ｲﾝﾃﾞｯｸｽ",
    "providerId": "daiwa",
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.007755,
    "refReturn": {
      "oneYear": 0.3664399246832115,
      "threeYear": 2.2253453453453456,
      "fiveYear": 2.1980705097665556,
      "sinceInception": 7.055300000000001
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_topix",
    "name": "eMAXIS Slim 国内株式(TOPIX)",
    "providerId": "mufg",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00143,
    "refReturn": {
      "oneYear": 0.38596152919057025,
      "threeYear": 0.9246836714199638,
      "fiveYear": 1.0961720743711263,
      "sinceInception": 1.9051131770412288
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_total_world",
    "name": "楽天･全世界株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "tags": [
      "株式-為替ヘッジなし",
      "先進国・新興国（広域）"
    ],
    "expenseRatio": 0.00179,
    "refReturn": {
      "oneYear": 0.34942060887984394,
      "threeYear": 0.9755563662896753,
      "fiveYear": 1.321709303987423,
      "sinceInception": 2.249
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_all_country_ex_japan",
    "name": "eMAXIS Slim 全世界株式(除く日本)",
    "providerId": "mufg",
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.0005775,
    "refReturn": {
      "oneYear": 0.34554789151904686,
      "threeYear": 1.0150839300387369,
      "fiveYear": 1.4273897058823528,
      "sinceInception": 2.4425950065175974
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_dev_ex_japan",
    "name": "eMAXIS Slim 先進国株式ｲﾝﾃﾞｯｸｽ(除く日本)",
    "providerId": "mufg",
    "tags": [
      "先進国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.0009889,
    "refReturn": {
      "oneYear": 0.3262061761441535,
      "threeYear": 1.0201382328079163,
      "fiveYear": 1.5298586462419825,
      "sinceInception": 3.09794230381279
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_plus_nikkei225",
    "name": "楽天･ﾌﾟﾗｽ･日経225ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00132,
    "refReturn": {
      "oneYear": 0.504260607136517,
      "sinceInception": 0.6970759062687764
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_nikkei225",
    "name": "eMAXIS Slim 国内株式(日経平均)",
    "providerId": "mufg",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00143,
    "refReturn": {
      "oneYear": 0.5048931383577053,
      "threeYear": 1.0389392669359139,
      "fiveYear": 0.9984315482859063,
      "sinceInception": 1.699727575421249
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "amone_tawara_nikkei225",
    "name": "たわらﾉｰﾛｰﾄﾞ 日経225",
    "providerId": "amone",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00143,
    "refReturn": {
      "oneYear": 0.5238095238095237,
      "threeYear": 1,
      "fiveYear": 1,
      "sinceInception": 2.2
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "amone_tawara_dev",
    "name": "たわらﾉｰﾛｰﾄﾞ先進国株式",
    "providerId": "amone",
    "tags": [
      "先進国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.0009889,
    "refReturn": {
      "oneYear": 0.34375,
      "threeYear": 1.0476190476190474,
      "fiveYear": 1.5294117647058822,
      "sinceInception": 3.3
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_emerging",
    "name": "eMAXIS Slim 新興国株式ｲﾝﾃﾞｯｸｽ",
    "providerId": "mufg",
    "tags": [
      "新興国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.001518,
    "refReturn": {
      "oneYear": 0.49416656323693675,
      "threeYear": 0.9511345218800649,
      "fiveYear": 0.8122083396055999,
      "sinceInception": 1.4371899989877517
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "daiwa_ifree_sp500",
    "name": "iFreeS&P500ｲﾝﾃﾞｯｸｽ",
    "providerId": "daiwa",
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.00198,
    "refReturn": {
      "oneYear": 0.31784671862305536,
      "threeYear": 1.0834403691546548,
      "fiveYear": 1.6531774398739927,
      "sinceInception": 3.3796
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_asset_building_aggressive",
    "name": "【らくらく投資専用】楽天･資産づくりﾌｧﾝﾄﾞ(しっかりｺｰｽ)",
    "providerId": "rakuten",
    "tags": [
      "バランス",
      "固定配分",
      "中リスク",
      "為替リスク低減"
    ],
    "expenseRatio": 0.004915,
    "refReturn": {
      "oneYear": 0.18057989485422965,
      "threeYear": 0.4920970502365851,
      "sinceInception": 0.4821
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "capital_world_equity_dc",
    "name": "ｷｬﾋﾟﾀﾙ世界株式ﾌｧﾝﾄﾞ(DC年金つみたて専用)",
    "providerId": "capital",
    "tags": [
      "先進国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.01085,
    "refReturn": {
      "oneYear": 0.3046877313512393,
      "threeYear": 0.90595258695276,
      "fiveYear": 1.092817784533536,
      "sinceInception": 3.4058
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_balance_8",
    "name": "eMAXIS Slimﾊﾞﾗﾝｽ(8資産均等型)",
    "providerId": "mufg",
    "tags": [
      "バランス",
      "固定配分",
      "中リスク",
      "為替リスク低減"
    ],
    "expenseRatio": 0.00143,
    "refReturn": {
      "oneYear": 0.2447951441578149,
      "threeYear": 0.5223814119219063,
      "fiveYear": 0.6269734232447441,
      "sinceInception": 1.0469108693482383
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "resona_smarti_sp500",
    "name": "Smart-i S&P500ｲﾝﾃﾞｯｸｽ",
    "providerId": "resona",
    "tags": [
      "北米",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.00242,
    "refReturn": {
      "oneYear": 0.3171776464522271,
      "threeYear": 1.0764036513692634,
      "fiveYear": 1.6250889257766183,
      "sinceInception": 2.321
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "smt_my_smt_sp500",
    "name": "My SMT S&P500ｲﾝﾃﾞｯｸｽ(ﾉｰﾛｰﾄﾞ)",
    "providerId": "smt",
    "tags": [
      "米国",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.000968,
    "refReturn": {
      "oneYear": 0.31925101619244356,
      "threeYear": 1.084,
      "sinceInception": 0.9798
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_tsumitate_topix",
    "name": "つみたて日本株式(TOPIX)",
    "providerId": "mufg",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00198,
    "refReturn": {
      "oneYear": 0.385148212284812,
      "threeYear": 0.9214356365691678,
      "fiveYear": 1.0908741446913202,
      "sinceInception": 1.71987198719872
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "sbi_total_world",
    "name": "SBI･全世界株式ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "sbi",
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.001022,
    "refReturn": {
      "oneYear": 0.3462243161889804,
      "threeYear": 0.9739973133755517,
      "sinceInception": 1.0761933595721063
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "smds_dc_tsumitate_japan",
    "name": "三井住友･DCつみたてNISA･日本株ｲﾝﾃﾞｯｸｽﾌｧﾝﾄﾞ",
    "providerId": "smds",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00176,
    "refReturn": {
      "oneYear": 0.3861085126286248,
      "threeYear": 0.923272072922505,
      "fiveYear": 1.093135995890587,
      "sinceInception": 5.586886239644373
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_high_dividend_nikkei",
    "name": "日経平均高配当利回り株ﾌｧﾝﾄﾞ",
    "providerId": "mufg",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00693,
    "refReturn": {
      "oneYear": 0.3276125595004149,
      "threeYear": 0.9361227869061266,
      "fiveYear": 1.919523672332661,
      "sinceInception": 2.048024864648085
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_tsumitate_balance_8",
    "name": "つみたて8資産均等ﾊﾞﾗﾝｽ",
    "providerId": "mufg",
    "tags": [
      "バランス型"
    ],
    "expenseRatio": 0.00242,
    "refReturn": {
      "oneYear": 0.2431045145330859,
      "threeYear": 0.5172856280193237,
      "fiveYear": 0.6190898107128473,
      "sinceInception": 1.005487379028235
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_tsumitate_nikkei",
    "name": "つみたて日本株式(日経平均)",
    "providerId": "mufg",
    "tags": [
      "国内",
      "株式"
    ],
    "expenseRatio": 0.00198,
    "refReturn": {
      "oneYear": 0.5040719295768017,
      "threeYear": 1.0356141692150866,
      "fiveYear": 0.9934489643124531,
      "sinceInception": 2.198938726471766
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_world_ex_us",
    "name": "楽天･全世界株式(除く米国)ｲﾝﾃﾞｯｸｽ･ﾌｧﾝﾄﾞ",
    "providerId": "rakuten",
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.00182,
    "refReturn": {
      "oneYear": 0.40299761871410555,
      "threeYear": 0.8758310703249368,
      "sinceInception": 1.0032
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "mufg_emaxis_slim_global_3region",
    "name": "eMAXIS Slim 全世界株式(3地域均等型)",
    "providerId": "mufg",
    "tags": [
      "先進国・新興国（広域）",
      "株式-為替ヘッジなし"
    ],
    "expenseRatio": 0.0005775,
    "refReturn": {
      "oneYear": 0.4005550874758388,
      "threeYear": 0.9710539164399805,
      "fiveYear": 1.1455470351529877,
      "sinceInception": 1.8553096898049914
    },
    "asOf": "2026-03-12"
  },
  {
    "id": "rakuten_asset_building_balanced",
    "name": "【らくらく投資専用】楽天･資産づくりﾌｧﾝﾄﾞ(なかなかｺｰｽ)",
    "providerId": "rakuten",
    "tags": [
      "バランス",
      "固定配分",
      "中リスク",
      "為替リスク低減"
    ],
    "expenseRatio": 0.004915,
    "refReturn": {
      "oneYear": 0.14754664823773322,
      "threeYear": 0.3827417508067035,
      "sinceInception": 0.3284
    },
    "asOf": "2026-03-12"
  }
];
