// tools/build-fund-analytics.ts

import fs from "node:fs";
import path from "node:path";
import iconv from "iconv-lite";

import { FUND_CONFIG } from "../data/fund-config";
import { computeFundAnalytics } from "../lib/analytics/compute-fund-analytics";
import type { FundAnalytics } from "../lib/analytics/types";
import { PARSERS } from "../lib/parsers";
import type { FundConfig, NormalizedNavRow } from "../lib/types";

const ROOT = process.cwd();
const NAV_CSV_DIR = path.join(ROOT, "data", "nav_csv");
const OUTPUT_PATH = path.join(ROOT, "data", "fund-analytics.ts");

type BuildSuccess = {
  ok: true;
  analytics: FundAnalytics;
};

type BuildFailure = {
  ok: false;
  fundId: string;
  providerId: string;
  reason: string;
};

type BuildResult = BuildSuccess | BuildFailure;

function readCsvText(filePath: string, providerId: string): string {
  const buf = fs.readFileSync(filePath);

  switch (providerId) {
    case "mufg":
    case "sbi":
    case "resona":
    case "rakuten":
    case "daiwa":
    case "capital":
      return iconv.decode(buf, "cp932");

    case "smt":
    case "smds":
    case "amone":
      return iconv.decode(buf, "utf-8");

    default:
      return iconv.decode(buf, "utf-8");
  }
}

function resolveCsvPath(config: FundConfig): string {
  return path.join(NAV_CSV_DIR, config.providerId, `${config.id}.csv`);
}

function validateRows(
  rows: NormalizedNavRow[],
  fundId: string
): NormalizedNavRow[] {
  if (rows.length === 0) {
    throw new Error(`No rows parsed: ${fundId}`);
  }

  const validRows = rows.filter((row) => {
    return (
      typeof row.date === "string" &&
      row.date.length > 0 &&
      Number.isFinite(row.nav) &&
      Number.isFinite(row.adjustedNav) &&
      Number.isFinite(row.dividend)
    );
  });

  if (validRows.length === 0) {
    throw new Error(`No valid rows: ${fundId}`);
  }

  const uniqueByDate = new Map<string, NormalizedNavRow>();

  for (const row of validRows) {
    uniqueByDate.set(row.date, row);
  }

  return [...uniqueByDate.values()].sort((a, b) =>
    a.date.localeCompare(b.date)
  );
}

function buildOne(config: FundConfig): BuildResult {
  try {
    const parser = PARSERS[config.providerId];
    if (!parser) {
      return {
        ok: false,
        fundId: config.id,
        providerId: config.providerId,
        reason: "Parser not found",
      };
    }

    const csvPath = resolveCsvPath(config);
    if (!fs.existsSync(csvPath)) {
      return {
        ok: false,
        fundId: config.id,
        providerId: config.providerId,
        reason: `CSV not found: ${csvPath}`,
      };
    }

    const csvText = readCsvText(csvPath, config.providerId);
    const parsedRows = parser(csvText);
    const rows = validateRows(parsedRows, config.id);

    const analytics = computeFundAnalytics(config.id, rows);

    return {
      ok: true,
      analytics,
    };
  } catch (error) {
    return {
      ok: false,
      fundId: config.id,
      providerId: config.providerId,
      reason: error instanceof Error ? error.message : String(error),
    };
  }
}

function generateModule(items: FundAnalytics[]): string {
  return `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/build-fund-analytics.ts

import type { FundAnalytics } from "../lib/analytics/types";

export const FUND_ANALYTICS: FundAnalytics[] = ${JSON.stringify(items, null, 2)};

export const FUND_ANALYTICS_BY_ID: Record<string, FundAnalytics> = Object.fromEntries(
  FUND_ANALYTICS.map((item) => [item.id, item])
);
`;
}

function main() {
  const strict = process.argv.includes("--strict");

  const filterIdArg = process.argv.find((arg) => arg.startsWith("--id="));
  const filterId = filterIdArg?.slice("--id=".length);

  const filterProviderArg = process.argv.find((arg) =>
    arg.startsWith("--provider=")
  );
  const filterProvider = filterProviderArg?.slice("--provider=".length);

  const targets = FUND_CONFIG.filter((config) => {
    if (filterId && config.id !== filterId) return false;
    if (filterProvider && config.providerId !== filterProvider) return false;
    return true;
  });

  const results = targets.map(buildOne);

  const analyticsItems = results
    .filter((result): result is BuildSuccess => result.ok)
    .map((result) => result.analytics);

  fs.writeFileSync(OUTPUT_PATH, generateModule(analyticsItems), "utf-8");

  const failed = results.filter((result): result is BuildFailure => !result.ok);

  console.log("=== build-fund-analytics ===");
  console.log(`Output : ${OUTPUT_PATH}`);
  console.log(`Total  : ${results.length}`);
  console.log(`Success: ${analyticsItems.length}`);
  console.log(`Failed : ${failed.length}`);

  if (failed.length > 0) {
    console.log("");
    console.log("Failures:");
    for (const f of failed) {
      console.log(`- [${f.providerId}] ${f.fundId}: ${f.reason}`);
    }
  }

  if (strict && failed.length > 0) {
    process.exit(1);
  }
}

main();