// tools/build-fund-config.ts

import fs from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";
import type { FundConfig } from "../lib/types";

type RawRow = Record<string, unknown>;

function getCell(row: RawRow, candidates: string[]): unknown {
  for (const key of candidates) {
    if (key in row) return row[key];
  }
  return undefined;
}

function toStringValue(value: unknown): string {
  if (value == null) return "";
  return String(value).trim();
}

function toNumberValue(value: unknown): number {
  if (value == null || value === "") return 0;
  if (typeof value === "number") return value;

  const cleaned = String(value).replace(/,/g, "").trim();
  const n = Number(cleaned);
  return Number.isFinite(n) ? n : 0;
}

function parseTags(value: unknown): string[] {
  const raw = toStringValue(value);
  if (!raw) return [];

  return raw
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean);
}

function assertRequired(value: string, label: string, rowIndex: number): string {
  if (!value) {
    throw new Error(`Row ${rowIndex}: ${label} が空です`);
  }
  return value;
}

function buildFundConfigFromRow(row: RawRow, rowIndex: number): FundConfig | null {
  const id = toStringValue(
    getCell(row, ["id/filename", "filename_id", "ファイル名（id）"])
  );
  const name = toStringValue(getCell(row, ["name"]));
  const providerId = toStringValue(getCell(row, ["provider_id"]));
  const expenseRatio = toNumberValue(getCell(row, ["expense_ratio", "管理費用"]));
  const tags = parseTags(getCell(row, ["tags", "tag", "タグ"]));
  const acquired = toStringValue(getCell(row, ["取得"]));

  // id が空の行はスキップ
  if (!id && !name && !providerId) return null;

  // 取得列があり、未取得のものを除外したい場合
  if (acquired && acquired !== "✅") {
    return null;
  }

  return {
    id: assertRequired(id, "id/filename", rowIndex),
    name: assertRequired(name, "name", rowIndex),
    providerId: assertRequired(providerId, "provider_id", rowIndex),
    expenseRatio,
    tags,
  };
}

function toTsModule(configs: FundConfig[]): string {
  return `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/build-fund-config.ts

import type { FundConfig } from "../lib/types";

export const FUND_CONFIG: FundConfig[] = ${JSON.stringify(configs, null, 2)};\n`;
}

function main() {
  const inputPath = path.join(process.cwd(), "data", "funds_master.xlsx");
  const outputPath = path.join(process.cwd(), "data", "fund-config.ts");

  if (!fs.existsSync(inputPath)) {
    throw new Error(`Excel file not found: ${inputPath}`);
  }

  const workbook = XLSX.readFile(inputPath);
  const sheetName = workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];

  const rows = XLSX.utils.sheet_to_json<RawRow>(sheet, {
    defval: "",
  });

  const configs: FundConfig[] = [];

  rows.forEach((row, index) => {
    const config = buildFundConfigFromRow(row, index + 2); // Excel上の行番号イメージ
    if (config) configs.push(config);
  });

  const ids = new Set<string>();
  for (const config of configs) {
    if (ids.has(config.id)) {
      throw new Error(`Duplicate id found: ${config.id}`);
    }
    ids.add(config.id);
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, toTsModule(configs), "utf-8");

  console.log("=== build-fund-config ===");
  console.log(`Output: ${outputPath}`);
  console.log(`Funds : ${configs.length}`);

}

main();