// tools/build-fund-config.ts

import fs from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";
import type { FundConfig } from "../lib/types";
import { EXPENSE_RATIOS } from "../data/expense-ratio";

type RawRow = Record<string, unknown>;

function getCell(row: RawRow, candidates: string[]): unknown {
  for (const key of candidates) {
    if (key in row) return row[key];
  }
  return undefined;
}

function toStringValue(value: unknown): string {
  if (value == null) return "";
  return String(value).trim();
}

function parseBooleanCell(value: unknown): boolean {
  if (typeof value === "boolean") return value;
  if (typeof value === "number") return value === 1;

  const normalized = String(value ?? "").trim().toLowerCase();
  return ["true", "1", "yes", "y"].includes(normalized);
}

function parseTags(value: unknown): string[] {
  const raw = toStringValue(value);
  if (!raw) return [];

  return raw
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean);
}

function assertRequired(value: string, label: string, rowIndex: number): string {
  if (!value) {
    throw new Error(`Row ${rowIndex}: ${label} が空です`);
  }
  return value;
}

function buildFundConfigFromRow(
  row: RawRow,
  rowIndex: number,
): FundConfig | null {
  const id = toStringValue(
    getCell(row, ["id/filename", "filename_id", "ファイル名（id）"]),
  );
  const name = toStringValue(getCell(row, ["name"]));
  const providerId = toStringValue(getCell(row, ["provider_id"]));
  const tags = parseTags(getCell(row, ["tags", "tag", "タグ"]));
  const acquired = toStringValue(getCell(row, ["取得"]));
  const expenseEnabled = parseBooleanCell(getCell(row, ["expense_enabled"]));

  if (!id && !name && !providerId) return null;

  if (acquired && acquired !== "✅") {
    return null;
  }

  const safeId = assertRequired(id, "id/filename", rowIndex);
  const safeName = assertRequired(name, "name", rowIndex);
  const safeProviderId = assertRequired(providerId, "provider_id", rowIndex);

  const expenseRatio = EXPENSE_RATIOS[safeId];

  if (expenseEnabled && typeof expenseRatio !== "number") {
    throw new Error(
      `Row ${rowIndex}: expense_enabled=true なのに EXPENSE_RATIOS に存在しません: ${safeId}`,
    );
  }

  return {
    id: safeId,
    name: safeName,
    providerId: safeProviderId,
    expenseRatio: expenseRatio ?? 0,
    tags,
  };
}

function toTsModule(configs: FundConfig[]): string {
  return `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/build-fund-config.ts

import type { FundConfig } from "../lib/types";

export const FUND_CONFIG: FundConfig[] = ${JSON.stringify(configs, null, 2)};\n`;
}

function main() {
  const inputPath = path.join(process.cwd(), "data", "funds_master.xlsx");
  const outputPath = path.join(process.cwd(), "data", "fund-config.ts");

  if (!fs.existsSync(inputPath)) {
    throw new Error(`Excel file not found: ${inputPath}`);
  }

  const workbook = XLSX.readFile(inputPath);
  const sheet = workbook.Sheets["funds"];

  if (!sheet) {
    throw new Error(`'funds' シートが見つかりません: ${inputPath}`);
  }

  const rows = XLSX.utils.sheet_to_json<RawRow>(sheet, { defval: "" });

  const configs: FundConfig[] = [];

  rows.forEach((row, index) => {
    const config = buildFundConfigFromRow(row, index + 2);
    if (config) configs.push(config);
  });

  const ids = new Set<string>();
  for (const config of configs) {
    if (ids.has(config.id)) {
      throw new Error(`Duplicate id found: ${config.id}`);
    }
    ids.add(config.id);
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, toTsModule(configs), "utf-8");

  console.log("=== build-fund-config ===");
  console.log(`Output: ${outputPath}`);
  console.log(`Funds : ${configs.length}`);
}

main();